import { type Locale } from "@/lib/i18n";

// Translations for the shared PageHeader (eyebrow / title / description) on the
// standalone app pages that have NO localized /xx/ URL (screener, ETF pages,
// picks, watchlist, news, staggered, …). PageHeader is a client component that
// looks each string up here by its English text and renders the chosen
// language (cookie/path locale). Pages keep passing English props; unmatched
// strings fall through to English. The /fr/ SEO views already pass localized
// header text server-side, so those don't need entries here.
type Tr = Partial<Record<Exclude<Locale, "en">, string>>;

const HEADER_I18N: Record<string, Tr> = {
  // --- Eyebrows ---
  "ETFs & Exposure": { fr: "ETF et exposition", de: "ETFs & Engagement", it: "ETF ed esposizione", es: "ETF y exposición" },
  "ETF Heatmap": { fr: "Carte de chaleur ETF", de: "ETF-Heatmap", it: "Mappa di calore ETF", es: "Mapa de calor ETF" },
  News: { fr: "Actualités", de: "Nachrichten", it: "Notizie", es: "Noticias" },
  Watchlist: { fr: "Liste de suivi", de: "Watchlist", it: "Watchlist", es: "Lista de seguimiento" },
  "Monthly Income": { fr: "Revenu mensuel", de: "Monatliches Einkommen", it: "Reddito mensile", es: "Ingreso mensual" },
  "Model Portfolio": { fr: "Portefeuille modèle", de: "Musterportfolio", it: "Portafoglio modello", es: "Cartera modelo" },

  // --- Titles ---
  "Best Dividend Stock Screener in 2026": { fr: "Meilleur screener d'actions à dividende en 2026", de: "Bester Dividenden-Aktien-Screener 2026", it: "Miglior screener di azioni da dividendo nel 2026", es: "Mejor screener de acciones por dividendo en 2026" },
  "Best Dividend Stock Screener in 2027": { fr: "Meilleur screener d'actions à dividende en 2027", de: "Bester Dividenden-Aktien-Screener 2027", it: "Miglior screener di azioni da dividendo nel 2027", es: "Mejor screener de acciones por dividendo en 2027" },
  "Which ETF owns a stock?": { fr: "Quel ETF détient une action ?", de: "Welcher ETF hält eine Aktie?", it: "Quale ETF detiene un'azione?", es: "¿Qué ETF posee una acción?" },
  "Stocks most held by ETFs": { fr: "Actions les plus détenues par les ETF", de: "Aktien, die am meisten von ETFs gehalten werden", it: "Azioni più detenute dagli ETF", es: "Acciones más mantenidas por ETF" },
  "Dividend & Market News": { fr: "Actualités dividendes et marchés", de: "Dividenden- & Marktnachrichten", it: "Notizie su dividendi e mercati", es: "Noticias de dividendos y mercados" },
  "My Dividend Watchlist": { fr: "Ma liste de suivi de dividendes", de: "Meine Dividenden-Watchlist", it: "La mia watchlist di dividendi", es: "Mi lista de seguimiento de dividendos" },
  "Monthly Payments from Quarterly Dividends": { fr: "Revenus mensuels à partir de dividendes trimestriels", de: "Monatliche Zahlungen aus Quartalsdividenden", it: "Pagamenti mensili da dividendi trimestrali", es: "Pagos mensuales a partir de dividendos trimestrales" },
  "Best Dividend Stocks Model Portfolio": { fr: "Portefeuille modèle des meilleures actions à dividende", de: "Musterportfolio der besten Dividenden-Aktien", it: "Portafoglio modello delle migliori azioni da dividendo", es: "Cartera modelo de las mejores acciones por dividendo" },
  "Best High Dividend Stocks": { fr: "Meilleures actions à haut rendement", de: "Beste Aktien mit hoher Dividende", it: "Migliori azioni ad alto dividendo", es: "Mejores acciones de alto dividendo" },
  "Best Dividend Growth Stocks": { fr: "Meilleures actions à dividende croissant", de: "Beste Dividendenwachstums-Aktien", it: "Migliori azioni a dividendo in crescita", es: "Mejores acciones de dividendo creciente" },
  "Best Dividend Protection": { fr: "Meilleure protection du dividende", de: "Bester Dividendenschutz", it: "Migliore protezione del dividendo", es: "Mejor protección del dividendo" },
  "Best Monthly Dividend Stocks": { fr: "Meilleures actions à dividende mensuel", de: "Beste monatliche Dividenden-Aktien", it: "Migliori azioni a dividendo mensile", es: "Mejores acciones de dividendo mensual" },
  "Best Dividend Capture Stocks": { fr: "Meilleures actions de capture de dividende", de: "Beste Dividenden-Capture-Aktien", it: "Migliori azioni di cattura del dividendo", es: "Mejores acciones de captura de dividendo" },

  // --- Descriptions ---
  "Find dividend stocks across sectors, currencies, and market caps. Filter by yield, size, and industry.": { fr: "Trouvez des actions à dividende par secteur, devise et capitalisation. Filtrez par rendement, taille et industrie.", de: "Finden Sie Dividenden-Aktien nach Sektor, Währung und Marktkapitalisierung. Filtern Sie nach Rendite, Größe und Branche.", it: "Trova azioni da dividendo per settore, valuta e capitalizzazione. Filtra per rendimento, dimensione e settore.", es: "Encuentra acciones por dividendo por sector, divisa y capitalización. Filtra por rentabilidad, tamaño e industria." },
  "Search any ticker or company name to see every ETF in our database that holds it — with each fund's weight, AUM, expense ratio, and position size.": { fr: "Recherchez un symbole ou un nom d'entreprise pour voir tous les ETF de notre base qui le détiennent — avec le poids, l'encours, les frais et la taille de position de chaque fonds.", de: "Suchen Sie einen Ticker oder Firmennamen, um jeden ETF in unserer Datenbank zu sehen, der ihn hält — mit Gewichtung, Volumen, Kostenquote und Positionsgröße jedes Fonds.", it: "Cerca un simbolo o il nome di una società per vedere ogni ETF nel nostro database che lo detiene — con peso, patrimonio, costi e dimensione della posizione di ciascun fondo.", es: "Busca un símbolo o nombre de empresa para ver todos los ETF de nuestra base que lo poseen — con el peso, patrimonio, comisiones y tamaño de posición de cada fondo." },
  "The 500 companies that show up in the most ETFs across our database, ordered by ETF count. Click any ticker to see exactly which funds hold it.": { fr: "Les 500 entreprises présentes dans le plus d'ETF de notre base, classées par nombre d'ETF. Cliquez sur un symbole pour voir exactement quels fonds le détiennent.", de: "Die 500 Unternehmen, die in den meisten ETFs unserer Datenbank vorkommen, nach ETF-Anzahl sortiert. Klicken Sie auf einen Ticker, um zu sehen, welche Fonds ihn halten.", it: "Le 500 società presenti nel maggior numero di ETF del nostro database, ordinate per numero di ETF. Clicca su un simbolo per vedere quali fondi lo detengono.", es: "Las 500 empresas que aparecen en más ETF de nuestra base, ordenadas por número de ETF. Haz clic en un símbolo para ver qué fondos lo poseen." },
  "Stay up to date with dividend declarations, payouts, and market commentary.": { fr: "Restez informé des déclarations de dividendes, des versements et de l'actualité des marchés.", de: "Bleiben Sie über Dividendenankündigungen, Auszahlungen und Marktkommentare auf dem Laufenden.", it: "Resta aggiornato su annunci di dividendi, pagamenti e commenti di mercato.", es: "Mantente al día de los anuncios de dividendos, los pagos y los comentarios del mercado." },
  "Track and compare your favorite dividend stocks in one place.": { fr: "Suivez et comparez vos actions à dividende préférées au même endroit.", de: "Verfolgen und vergleichen Sie Ihre bevorzugten Dividenden-Aktien an einem Ort.", it: "Segui e confronta le tue azioni da dividendo preferite in un unico posto.", es: "Sigue y compara tus acciones por dividendo favoritas en un solo lugar." },
  "Quarterly dividend payers split into 3 month buckets — buy across all 3 buckets and you receive a dividend every month of the year.": { fr: "Des payeurs trimestriels répartis en 3 groupes mensuels — achetez dans les 3 groupes et recevez un dividende chaque mois de l'année.", de: "Quartalszahler in 3 Monatsgruppen aufgeteilt — kaufen Sie aus allen 3 Gruppen und erhalten Sie jeden Monat eine Dividende.", it: "Pagatori trimestrali divisi in 3 gruppi mensili — acquista in tutti e 3 i gruppi e ricevi un dividendo ogni mese dell'anno.", es: "Pagadores trimestrales divididos en 3 grupos mensuales — compra en los 3 grupos y recibe un dividendo cada mes del año." },
  "A balanced blend of yield and total return — our flagship Model Portfolio. Ranked by composite rating.": { fr: "Un équilibre entre rendement et performance totale — notre portefeuille modèle phare. Classé par note composite.", de: "Eine ausgewogene Mischung aus Rendite und Gesamtertrag — unser Vorzeige-Musterportfolio. Nach Gesamtbewertung sortiert.", it: "Un equilibrio tra rendimento e rendimento totale — il nostro portafoglio modello di punta. Ordinato per valutazione composita.", es: "Un equilibrio entre rentabilidad y retorno total — nuestra cartera modelo insignia. Ordenada por calificación compuesta." },
  "Model portfolio targeting 6–12% dividend yield, ranked by composite rating (so we surface high-quality high-yield names, not yield traps).": { fr: "Portefeuille modèle visant un rendement de 6 à 12 %, classé par note composite (pour faire ressortir les titres de qualité, pas les pièges à rendement).", de: "Musterportfolio mit Ziel 6–12 % Dividendenrendite, nach Gesamtbewertung sortiert (um Qualitätswerte statt Renditefallen hervorzuheben).", it: "Portafoglio modello con obiettivo di rendimento 6–12 %, ordinato per valutazione composita (per far emergere titoli di qualità, non trappole da rendimento).", es: "Cartera modelo con objetivo de rentabilidad del 6–12 %, ordenada por calificación compuesta (para destacar valores de calidad, no trampas de rentabilidad)." },
  "Companies that consistently raise dividends — ranked by our Growth rating (1-5 scale) which weights revenue growth, EPS growth, and dividend CAGR.": { fr: "Des sociétés qui augmentent régulièrement leur dividende — classées par notre note de Croissance (échelle 1-5) qui pondère la croissance du chiffre d'affaires, du BPA et le CAGR du dividende.", de: "Unternehmen, die ihre Dividende stetig erhöhen — nach unserer Wachstumsbewertung (Skala 1-5) sortiert, die Umsatzwachstum, EPS-Wachstum und Dividenden-CAGR gewichtet.", it: "Società che aumentano costantemente i dividendi — ordinate secondo la nostra valutazione di Crescita (scala 1-5) che pesa crescita dei ricavi, dell'EPS e CAGR del dividendo.", es: "Empresas que aumentan sus dividendos de forma constante — ordenadas por nuestra calificación de Crecimiento (escala 1-5) que pondera el crecimiento de ingresos, del BPA y el CAGR del dividendo." },
  "Maximum safety — large-cap dividend payers with the highest Health rating (debt coverage, cash position, payout ratio).": { fr: "Sécurité maximale — des payeurs de dividende de grande capitalisation avec la meilleure note de Santé (couverture de la dette, trésorerie, ratio de distribution).", de: "Maximale Sicherheit — Large-Cap-Dividendenzahler mit der höchsten Gesundheitsbewertung (Schuldendeckung, Liquidität, Ausschüttungsquote).", it: "Massima sicurezza — pagatori di dividendi a grande capitalizzazione con la più alta valutazione di Salute (copertura del debito, liquidità, payout).", es: "Máxima seguridad — pagadores de dividendos de gran capitalización con la mejor calificación de Salud (cobertura de deuda, liquidez, pay-out)." },
  "Top-rated monthly dividend payers for steady income — ranked by composite rating.": { fr: "Les payeurs de dividende mensuel les mieux notés pour un revenu régulier — classés par note composite.", de: "Bestbewertete monatliche Dividendenzahler für stetiges Einkommen — nach Gesamtbewertung sortiert.", it: "I pagatori di dividendi mensili più votati per un reddito costante — ordinati per valutazione composita.", es: "Los pagadores de dividendos mensuales mejor valorados para ingresos constantes — ordenados por calificación compuesta." },
  "Stable high-yield dividend payers with strong Momentum scores — quick to recover from ex-dividend drops, making them ideal capture candidates.": { fr: "Des payeurs de dividende à haut rendement stables avec un fort score de Momentum — qui récupèrent vite après le détachement, ce qui en fait des candidats idéaux à la capture.", de: "Stabile, renditestarke Dividendenzahler mit starken Momentum-Werten — erholen sich schnell von Ex-Dividenden-Abschlägen und sind so ideale Capture-Kandidaten.", it: "Pagatori di dividendi ad alto rendimento stabili con forti punteggi di Momentum — recuperano rapidamente dopo lo stacco, ideali per la strategia di cattura.", es: "Pagadores de dividendos de alta rentabilidad estables con fuertes puntuaciones de Momentum — se recuperan rápido tras el ex-dividendo, ideales para la captura." },
};

/** Translate a PageHeader string by its English text; English falls through. */
export function tHeader(text: string | undefined, locale: Locale): string | undefined {
  if (!text || locale === "en") return text;
  return HEADER_I18N[text]?.[locale] ?? text;
}
