import type { Locale } from "@/lib/i18n";

// Generator UI chrome, localized. Engine-generated prose (thesis, notes) and
// variant names stay English for now; the AI layers answer in the user's
// language via a locale param. SSR renders English; locale applies on
// hydration (use-locale.ts).
export type Seg = { label: string; sub: string };
export type GenStr = {
  heroKicker: string; heroFree: string; heroTitle: string; heroSub: string; heroValidation: string;
  emptyTitle: string; emptySub: string; emptyChips: [string, string, string];
  pipeGoal: string; pipeGoalSub: string; pipeScreen: string; pipeScreenSub: string;
  pipeOpt: string; pipeOptSub: string; pipeMeasure: string; pipeMeasureSub: string; pipeFooter: string;
  panelTitle: string; loadErr: string;
  s1: string; s2: string; s2hint: string; s3: string;
  amountLabel: string; riskLabel: string; objLabel: string; horizonLabel: string;
  risk: [Seg, Seg, Seg]; obj: [Seg, Seg, Seg]; horizon: [Seg, Seg, Seg];
  goalLabel: string; goalHint: string; goalPh: string; goalChips: [string, string, string, string];
  targetLabel: string; targetHint: string; monthlyLabel: string; monthlyHint: string; monthlyPh: string;
  marketLabel: string; marketHint: string; marketModalTitle: string; marketModalSub: string; marketDone: string; marketGlobal: string; marketSelected: (n: number, max: number) => string;
  sectorsLabel: string; sectorsHint: string;
  anchorsLabel: string; anchorsHint: string; anchorsPh: string; anchorsPhMore: string; allTickers: string;
  countLabel: string; countFocused: string; countSpread: string;
  generate: string; regenerate: string; building: string;
  // results chrome
  yourPortfolio: string; optimizationMeta: (label: string, n: number, amount: string) => string;
  measured: string; measuring: string; modelled: string; blOptimized: string; costToImplement: (bps: number) => string; aiRead: string;
  thesis: string; frontier: string; corr: string; assetMix: string; allocation: string;
  thHolding: string; thRating: string; thWeight: string; thAmount: string; thYield: string;
  stats: string; monteCarlo: string; backtest: string; stress: string; riskContrib: string;
  factor: string; sectorExposure: string; whyGrade: string; audit: string; analysis: string; picksWhy: string; legendary: string;
  downloadCsv: string; openHealthcheck: string;
  bannerTitle: string; bannerSub: string; bannerCtaPro: string; bannerCtaFree: string;
  lockedStressTitle: string; lockedRiskTitle: string; lockedCorrTitle: string; lockedWhyTitle: string;
  unlockPro: string; unlockFooter: string;
  freePreview: string; bannerLineA: string; bannerLineB: string; seePlans: string;
};

const seg = (label: string, sub: string): Seg => ({ label, sub });

export const GEN_STR: Record<Locale, GenStr> = {
  en: {
    heroKicker: "Tools", heroFree: " · Free",
    heroTitle: "Portfolio generator",
    heroSub: "Answer a few questions — or pin the stocks and ETFs you already love — and we'll build a diversified, top-rated portfolio sized to your amount.",
    heroValidation: "Does it work? See the live walk-forward track record →",
    emptyTitle: "Set your preferences, then generate",
    emptySub: "We'll build a diversified, top-rated portfolio — optimised for the best risk-adjusted return, sized to your amount, and built around any holdings you pin.",
    emptyChips: ["Rated holdings", "Smart weighting", "Monte Carlo projection"],
    pipeGoal: "AI reading your goal & selecting candidates", pipeGoalSub: "queries the rated universe with your constraints",
    pipeScreen: "Screening the rated universe", pipeScreenSub: "every liquid payer, ranked by composite grade",
    pipeOpt: "Black–Litterman optimization", pipeOptSub: "equilibrium prior + rating & analyst views → solved weights",
    pipeMeasure: "Measuring against 10 years of real closes", pipeMeasureSub: "backtest, crisis replays, correlations, factor exposures",
    pipeFooter: "COMPUTED LIVE — NOTHING IS PREMADE",
    panelTitle: "Build your portfolio", loadErr: "Could not load live market data — refresh to try again.",
    s1: "The basics", s2: "Your goal", s2hint: "optional", s3: "Refine the build",
    amountLabel: "How much do you want to invest?", riskLabel: "Risk tolerance", objLabel: "What matters more?", horizonLabel: "Time horizon",
    risk: [seg("Conservative", "Lower swings, ballast"), seg("Balanced", "A middle path"), seg("Aggressive", "More risk for return")],
    obj: [seg("Income", "Higher dividend yield"), seg("Balanced", "Income + growth"), seg("Growth", "Capital appreciation")],
    horizon: [seg("< 5 yrs", "More ballast"), seg("5–15 yrs", "Balanced"), seg("15+ yrs", "More equity")],
    goalLabel: "Describe your goal", goalHint: "we read this and tilt the picks",
    goalPh: "e.g. Retirement nest egg for a 45-year-old. Broad equity with bond ballast and some international. Comfortable through a 25% drawdown, not 40%.",
    goalChips: ["dividend income", "tech innovation", "international", "capital preservation"],
    targetLabel: "Target wealth", targetHint: "what you want to end up with", monthlyLabel: "Monthly top-up", monthlyHint: "added every month", monthlyPh: "e.g. 100",
    marketLabel: "Market focus", marketHint: "stocks from this market; core ETFs stay global",
    marketModalTitle: "Market focus", marketModalSub: "Pick up to 4 markets — or leave it global. Core ETFs stay global either way.", marketDone: "Done",
    marketGlobal: "No preference · Global", marketSelected: (n, max) => (n === 0 ? "Global" : `${n} selected · max ${max}`),
    sectorsLabel: "Favour any sectors?", sectorsHint: "leave blank for all",
    anchorsLabel: "Build around specific holdings?", anchorsHint: "we'll build the rest around them",
    anchorsPh: "Search a stock or ETF — e.g. AAPL, SCHD, O", anchorsPhMore: "Add another…", allTickers: "All tickers",
    countLabel: "Number of holdings", countFocused: "5 · focused", countSpread: "20 · spread out",
    generate: "Generate my portfolio", regenerate: "Regenerate", building: "Building — pulling live market data…",
    yourPortfolio: "Your generated portfolio",
    optimizationMeta: (label, n, amount) => `${label} optimization · ${n} holdings · sized to ${amount}`,
    measured: "MEASURED · REAL PRICE HISTORY", measuring: "MEASURING…", modelled: "MODEL ESTIMATES", blOptimized: "BLACK–LITTERMAN OPTIMIZED",
    costToImplement: (bps) => `est. cost to implement ~${bps} bps`, aiRead: "AI READ:",
    thesis: "Portfolio thesis", frontier: "Six frontier portfolios", corr: "Correlation matrix", assetMix: "Asset mix", allocation: "Recommended allocation",
    thHolding: "Holding", thRating: "Rating", thWeight: "Weight", thAmount: "Amount", thYield: "Yield",
    stats: "The eight stats that matter", monteCarlo: "Monte Carlo projection", backtest: "Historical backtest · real daily closes",
    stress: "Historical stress tests", riskContrib: "Risk contribution", factor: "Factor exposure · vs S&P 500", sectorExposure: "Sector exposure",
    whyGrade: "Why this grade", audit: "AI audit · live ratings & news", analysis: "AI analysis", picksWhy: "Why these picks", legendary: "Legendary portfolio comparison",
    downloadCsv: "Download allocation (CSV)", openHealthcheck: "Open in Healthcheck",
    bannerTitle: "You're on the free preview", bannerSub: "Generate freely — upgrade to reveal every holding and the full risk toolkit.",
    bannerCtaPro: "Unlock with Pro", bannerCtaFree: "Create a free account",
    lockedStressTitle: "Stress-test against every modern crisis", lockedRiskTitle: "Find your hidden risk drivers",
    lockedCorrTitle: "See what really diversifies", lockedWhyTitle: "See the full per-holding reasoning",
    unlockPro: "Unlock with Pro", unlockFooter: "Unlock every holding, stress tests, correlation & the full rationale.",
    freePreview: "FREE PREVIEW", bannerLineA: "You can generate freely — ", bannerLineB: " reveals every holding and unlocks stress tests, correlation & the full rationale.", seePlans: "See plans",
  },
  fr: {
    heroKicker: "Outils", heroFree: " · Gratuit",
    heroTitle: "Générateur de portefeuille",
    heroSub: "Répondez à quelques questions — ou épinglez les actions et ETF que vous aimez déjà — et nous construisons un portefeuille diversifié et bien noté, à la taille de votre montant.",
    heroValidation: "Ça marche ? Voir l'historique de validation en direct →",
    emptyTitle: "Réglez vos préférences, puis générez",
    emptySub: "Nous construirons un portefeuille diversifié et bien noté — optimisé pour le meilleur rendement ajusté du risque, à la taille de votre montant, autour des positions que vous épinglez.",
    emptyChips: ["Titres notés", "Pondération intelligente", "Projection Monte Carlo"],
    pipeGoal: "L'IA lit votre objectif et sélectionne les candidats", pipeGoalSub: "interroge l'univers noté avec vos contraintes",
    pipeScreen: "Filtrage de l'univers noté", pipeScreenSub: "chaque payeur liquide, classé par note composite",
    pipeOpt: "Optimisation Black–Litterman", pipeOptSub: "prior d'équilibre + vues notations & analystes → poids résolus",
    pipeMeasure: "Mesure sur 10 ans de cours réels", pipeMeasureSub: "backtest, crises rejouées, corrélations, expositions factorielles",
    pipeFooter: "CALCULÉ EN DIRECT — RIEN N'EST PRÉFABRIQUÉ",
    panelTitle: "Construisez votre portefeuille", loadErr: "Impossible de charger les données de marché — rafraîchissez pour réessayer.",
    s1: "Les bases", s2: "Votre objectif", s2hint: "optionnel", s3: "Affiner la construction",
    amountLabel: "Combien voulez-vous investir ?", riskLabel: "Tolérance au risque", objLabel: "Qu'est-ce qui compte le plus ?", horizonLabel: "Horizon de temps",
    risk: [seg("Prudent", "Moins de secousses, du lest"), seg("Équilibré", "La voie médiane"), seg("Agressif", "Plus de risque pour le rendement")],
    obj: [seg("Revenu", "Rendement du dividende plus élevé"), seg("Équilibré", "Revenu + croissance"), seg("Croissance", "Appréciation du capital")],
    horizon: [seg("< 5 ans", "Plus de lest"), seg("5–15 ans", "Équilibré"), seg("15+ ans", "Plus d'actions")],
    goalLabel: "Décrivez votre objectif", goalHint: "nous le lisons et orientons les choix",
    goalPh: "ex. Épargne retraite d'un quadragénaire. Actions larges avec lest obligataire et un peu d'international. À l'aise avec −25 %, pas −40 %.",
    goalChips: ["revenu de dividendes", "innovation tech", "international", "préservation du capital"],
    targetLabel: "Patrimoine cible", targetHint: "ce que vous voulez atteindre", monthlyLabel: "Versement mensuel", monthlyHint: "ajouté chaque mois", monthlyPh: "ex. 100",
    marketLabel: "Marché ciblé", marketHint: "actions de ce marché ; les ETF cœur restent globaux",
    marketModalTitle: "Marché ciblé", marketModalSub: "Choisissez jusqu'à 4 marchés — ou laissez global. Les ETF cœur restent globaux.", marketDone: "Valider",
    marketGlobal: "Sans préférence · Global", marketSelected: (n, max) => (n === 0 ? "Global" : `${n} sélectionné(s) · max ${max}`),
    sectorsLabel: "Privilégier des secteurs ?", sectorsHint: "vide = tous",
    anchorsLabel: "Construire autour de positions précises ?", anchorsHint: "nous bâtirons le reste autour",
    anchorsPh: "Cherchez une action ou un ETF — ex. AAPL, SCHD, O", anchorsPhMore: "En ajouter un autre…", allTickers: "Tous les titres",
    countLabel: "Nombre de positions", countFocused: "5 · concentré", countSpread: "20 · étalé",
    generate: "Générer mon portefeuille", regenerate: "Régénérer", building: "Construction — données de marché en cours…",
    yourPortfolio: "Votre portefeuille généré",
    optimizationMeta: (label, n, amount) => `Optimisation ${label} · ${n} positions · pour ${amount}`,
    measured: "MESURÉ · HISTORIQUE RÉEL", measuring: "MESURE…", modelled: "ESTIMATIONS MODÈLE", blOptimized: "OPTIMISÉ BLACK–LITTERMAN",
    costToImplement: (bps) => `coût d'implémentation estimé ~${bps} pb`, aiRead: "L'IA A LU :",
    thesis: "Thèse du portefeuille", frontier: "Six portefeuilles de frontière", corr: "Matrice de corrélation", assetMix: "Répartition d'actifs", allocation: "Allocation recommandée",
    thHolding: "Position", thRating: "Note", thWeight: "Poids", thAmount: "Montant", thYield: "Rendement",
    stats: "Les huit chiffres qui comptent", monteCarlo: "Projection Monte Carlo", backtest: "Backtest historique · cours réels",
    stress: "Stress tests historiques", riskContrib: "Contribution au risque", factor: "Exposition factorielle · vs S&P 500", sectorExposure: "Exposition sectorielle",
    whyGrade: "Pourquoi cette note", audit: "Audit IA · notations & actus en direct", analysis: "Analyse IA", picksWhy: "Pourquoi ces choix", legendary: "Comparaison aux portefeuilles légendaires",
    downloadCsv: "Télécharger l'allocation (CSV)", openHealthcheck: "Ouvrir dans le Bilan",
    bannerTitle: "Vous êtes sur l'aperçu gratuit", bannerSub: "Générez librement — passez Pro pour révéler chaque position et tout l'outillage de risque.",
    bannerCtaPro: "Débloquer avec Pro", bannerCtaFree: "Créer un compte gratuit",
    lockedStressTitle: "Testez contre chaque crise moderne", lockedRiskTitle: "Trouvez vos moteurs de risque cachés",
    lockedCorrTitle: "Voyez ce qui diversifie vraiment", lockedWhyTitle: "Voyez le raisonnement par position",
    unlockPro: "Débloquer avec Pro", unlockFooter: "Débloquez chaque position, les stress tests, la corrélation et toute la logique.",
    freePreview: "APERÇU GRATUIT", bannerLineA: "Générez librement — ", bannerLineB: " révèle chaque position et débloque stress tests, corrélation et toute la logique.", seePlans: "Voir les offres",
  },
  de: {
    heroKicker: "Tools", heroFree: " · Gratis",
    heroTitle: "Portfolio-Generator",
    heroSub: "Beantworte ein paar Fragen — oder pinne Aktien und ETFs, die du schon magst — und wir bauen ein diversifiziertes, top-bewertetes Portfolio in deiner Größe.",
    heroValidation: "Funktioniert das? Live-Track-Record ansehen →",
    emptyTitle: "Präferenzen einstellen, dann generieren",
    emptySub: "Wir bauen ein diversifiziertes, top-bewertetes Portfolio — optimiert auf das beste risikoadjustierte Ergebnis, in deiner Größe, um deine gepinnten Positionen herum.",
    emptyChips: ["Bewertete Titel", "Intelligente Gewichtung", "Monte-Carlo-Projektion"],
    pipeGoal: "KI liest dein Ziel & wählt Kandidaten", pipeGoalSub: "fragt das bewertete Universum mit deinen Vorgaben ab",
    pipeScreen: "Screening des bewerteten Universums", pipeScreenSub: "jeder liquide Zahler, nach Composite-Note gerankt",
    pipeOpt: "Black–Litterman-Optimierung", pipeOptSub: "Gleichgewichts-Prior + Rating- & Analystensichten → gelöste Gewichte",
    pipeMeasure: "Messung an 10 Jahren echter Kurse", pipeMeasureSub: "Backtest, Krisen-Replays, Korrelationen, Faktorexposures",
    pipeFooter: "LIVE BERECHNET — NICHTS IST VORGEFERTIGT",
    panelTitle: "Baue dein Portfolio", loadErr: "Marktdaten konnten nicht geladen werden — bitte Seite neu laden.",
    s1: "Die Basics", s2: "Dein Ziel", s2hint: "optional", s3: "Feinschliff",
    amountLabel: "Wie viel willst du investieren?", riskLabel: "Risikotoleranz", objLabel: "Was zählt mehr?", horizonLabel: "Zeithorizont",
    risk: [seg("Konservativ", "Weniger Schwankung, Ballast"), seg("Ausgewogen", "Der Mittelweg"), seg("Aggressiv", "Mehr Risiko für Rendite")],
    obj: [seg("Einkommen", "Höhere Dividendenrendite"), seg("Ausgewogen", "Einkommen + Wachstum"), seg("Wachstum", "Kurssteigerung")],
    horizon: [seg("< 5 J.", "Mehr Ballast"), seg("5–15 J.", "Ausgewogen"), seg("15+ J.", "Mehr Aktien")],
    goalLabel: "Beschreibe dein Ziel", goalHint: "wir lesen es und richten die Auswahl danach aus",
    goalPh: "z. B. Altersvorsorge mit 45. Breite Aktien mit Anleihen-Ballast und etwas international. −25 % okay, −40 % nicht.",
    goalChips: ["Dividendeneinkommen", "Tech-Innovation", "international", "Kapitalerhalt"],
    targetLabel: "Zielvermögen", targetHint: "was am Ende stehen soll", monthlyLabel: "Monatliche Sparrate", monthlyHint: "jeden Monat dazu", monthlyPh: "z. B. 100",
    marketLabel: "Marktfokus", marketHint: "Aktien aus diesem Markt; Kern-ETFs bleiben global",
    marketModalTitle: "Marktfokus", marketModalSub: "Bis zu 4 Märkte wählen — oder global lassen. Kern-ETFs bleiben ohnehin global.", marketDone: "Fertig",
    marketGlobal: "Keine Präferenz · Global", marketSelected: (n, max) => (n === 0 ? "Global" : `${n} gewählt · max. ${max}`),
    sectorsLabel: "Sektoren bevorzugen?", sectorsHint: "leer = alle",
    anchorsLabel: "Um bestimmte Positionen herum bauen?", anchorsHint: "wir bauen den Rest darum herum",
    anchorsPh: "Aktie oder ETF suchen — z. B. AAPL, SCHD, O", anchorsPhMore: "Weitere hinzufügen…", allTickers: "Alle Titel",
    countLabel: "Anzahl Positionen", countFocused: "5 · fokussiert", countSpread: "20 · breit gestreut",
    generate: "Portfolio generieren", regenerate: "Neu generieren", building: "Baue — lade Live-Marktdaten…",
    yourPortfolio: "Dein generiertes Portfolio",
    optimizationMeta: (label, n, amount) => `${label}-Optimierung · ${n} Positionen · für ${amount}`,
    measured: "GEMESSEN · ECHTE KURSHISTORIE", measuring: "MESSE…", modelled: "MODELL-SCHÄTZUNGEN", blOptimized: "BLACK–LITTERMAN-OPTIMIERT",
    costToImplement: (bps) => `geschätzte Umsetzungskosten ~${bps} Bp`, aiRead: "KI HAT GELESEN:",
    thesis: "Portfolio-These", frontier: "Sechs Frontier-Portfolios", corr: "Korrelationsmatrix", assetMix: "Asset-Mix", allocation: "Empfohlene Allokation",
    thHolding: "Position", thRating: "Note", thWeight: "Gewicht", thAmount: "Betrag", thYield: "Rendite",
    stats: "Die acht Zahlen, die zählen", monteCarlo: "Monte-Carlo-Projektion", backtest: "Historischer Backtest · echte Tageskurse",
    stress: "Historische Stresstests", riskContrib: "Risikobeitrag", factor: "Faktorexposure · vs. S&P 500", sectorExposure: "Sektor-Exposure",
    whyGrade: "Warum diese Note", audit: "KI-Audit · Live-Ratings & News", analysis: "KI-Analyse", picksWhy: "Warum diese Auswahl", legendary: "Vergleich mit legendären Portfolios",
    downloadCsv: "Allokation herunterladen (CSV)", openHealthcheck: "Im Portfolio-Check öffnen",
    bannerTitle: "Du bist in der Gratis-Vorschau", bannerSub: "Generiere frei — mit Pro siehst du jede Position und das volle Risiko-Toolkit.",
    bannerCtaPro: "Mit Pro freischalten", bannerCtaFree: "Gratis-Konto erstellen",
    lockedStressTitle: "Gegen jede moderne Krise stresstesten", lockedRiskTitle: "Versteckte Risikotreiber finden",
    lockedCorrTitle: "Sehen, was wirklich diversifiziert", lockedWhyTitle: "Die volle Begründung je Position sehen",
    unlockPro: "Mit Pro freischalten", unlockFooter: "Jede Position, Stresstests, Korrelation & die volle Logik freischalten.",
    freePreview: "GRATIS-VORSCHAU", bannerLineA: "Du kannst frei generieren — ", bannerLineB: " zeigt jede Position und schaltet Stresstests, Korrelation & die volle Logik frei.", seePlans: "Tarife ansehen",
  },
  es: {
    heroKicker: "Herramientas", heroFree: " · Gratis",
    heroTitle: "Generador de carteras",
    heroSub: "Responde unas preguntas — o fija las acciones y ETFs que ya te gustan — y construiremos una cartera diversificada y bien calificada al tamaño de tu importe.",
    heroValidation: "¿Funciona? Mira el historial de validación en vivo →",
    emptyTitle: "Ajusta tus preferencias y genera",
    emptySub: "Construiremos una cartera diversificada y bien calificada — optimizada para la mejor rentabilidad ajustada al riesgo, a tu medida y alrededor de las posiciones que fijes.",
    emptyChips: ["Valores calificados", "Ponderación inteligente", "Proyección Monte Carlo"],
    pipeGoal: "La IA lee tu objetivo y selecciona candidatos", pipeGoalSub: "consulta el universo calificado con tus restricciones",
    pipeScreen: "Filtrando el universo calificado", pipeScreenSub: "cada pagador líquido, ordenado por nota compuesta",
    pipeOpt: "Optimización Black–Litterman", pipeOptSub: "prior de equilibrio + vistas de rating y analistas → pesos resueltos",
    pipeMeasure: "Midiendo contra 10 años de cierres reales", pipeMeasureSub: "backtest, crisis reproducidas, correlaciones, factores",
    pipeFooter: "CALCULADO EN VIVO — NADA ESTÁ PREFABRICADO",
    panelTitle: "Construye tu cartera", loadErr: "No se pudieron cargar los datos de mercado — recarga para reintentar.",
    s1: "Lo básico", s2: "Tu objetivo", s2hint: "opcional", s3: "Afinar la construcción",
    amountLabel: "¿Cuánto quieres invertir?", riskLabel: "Tolerancia al riesgo", objLabel: "¿Qué importa más?", horizonLabel: "Horizonte temporal",
    risk: [seg("Conservador", "Menos vaivenes, lastre"), seg("Equilibrado", "El camino medio"), seg("Agresivo", "Más riesgo por rentabilidad")],
    obj: [seg("Ingresos", "Mayor rentabilidad por dividendo"), seg("Equilibrado", "Ingresos + crecimiento"), seg("Crecimiento", "Apreciación del capital")],
    horizon: [seg("< 5 años", "Más lastre"), seg("5–15 años", "Equilibrado"), seg("15+ años", "Más renta variable")],
    goalLabel: "Describe tu objetivo", goalHint: "lo leemos y orientamos la selección",
    goalPh: "p. ej. Ahorro de jubilación de un cuarentón. Renta variable amplia con lastre de bonos y algo internacional. Cómodo con −25%, no con −40%.",
    goalChips: ["ingresos por dividendos", "innovación tecnológica", "internacional", "preservación del capital"],
    targetLabel: "Patrimonio objetivo", targetHint: "con cuánto quieres acabar", monthlyLabel: "Aportación mensual", monthlyHint: "añadida cada mes", monthlyPh: "p. ej. 100",
    marketLabel: "Mercado objetivo", marketHint: "acciones de ese mercado; los ETFs núcleo siguen globales",
    marketModalTitle: "Mercado objetivo", marketModalSub: "Elige hasta 4 mercados — o déjalo global. Los ETFs núcleo siguen globales.", marketDone: "Hecho",
    marketGlobal: "Sin preferencia · Global", marketSelected: (n, max) => (n === 0 ? "Global" : `${n} seleccionados · máx. ${max}`),
    sectorsLabel: "¿Favorecer sectores?", sectorsHint: "en blanco = todos",
    anchorsLabel: "¿Construir alrededor de posiciones concretas?", anchorsHint: "construiremos el resto a su alrededor",
    anchorsPh: "Busca una acción o ETF — p. ej. AAPL, SCHD, O", anchorsPhMore: "Añadir otra…", allTickers: "Todos los valores",
    countLabel: "Número de posiciones", countFocused: "5 · concentrado", countSpread: "20 · repartido",
    generate: "Generar mi cartera", regenerate: "Regenerar", building: "Construyendo — cargando datos de mercado…",
    yourPortfolio: "Tu cartera generada",
    optimizationMeta: (label, n, amount) => `Optimización ${label} · ${n} posiciones · para ${amount}`,
    measured: "MEDIDO · HISTÓRICO REAL", measuring: "MIDIENDO…", modelled: "ESTIMACIONES DEL MODELO", blOptimized: "OPTIMIZADO BLACK–LITTERMAN",
    costToImplement: (bps) => `coste estimado de implementación ~${bps} pb`, aiRead: "LA IA LEYÓ:",
    thesis: "Tesis de la cartera", frontier: "Seis carteras de la frontera", corr: "Matriz de correlación", assetMix: "Mezcla de activos", allocation: "Asignación recomendada",
    thHolding: "Posición", thRating: "Nota", thWeight: "Peso", thAmount: "Importe", thYield: "Rentab.",
    stats: "Las ocho cifras que importan", monteCarlo: "Proyección Monte Carlo", backtest: "Backtest histórico · cierres reales",
    stress: "Stress tests históricos", riskContrib: "Contribución al riesgo", factor: "Exposición factorial · vs S&P 500", sectorExposure: "Exposición sectorial",
    whyGrade: "Por qué esta nota", audit: "Auditoría IA · ratings y noticias en vivo", analysis: "Análisis IA", picksWhy: "Por qué estas elecciones", legendary: "Comparación con carteras legendarias",
    downloadCsv: "Descargar asignación (CSV)", openHealthcheck: "Abrir en el Chequeo",
    bannerTitle: "Estás en la vista previa gratis", bannerSub: "Genera libremente — mejora a Pro para revelar cada posición y todo el kit de riesgo.",
    bannerCtaPro: "Desbloquear con Pro", bannerCtaFree: "Crear cuenta gratis",
    lockedStressTitle: "Stress test contra cada crisis moderna", lockedRiskTitle: "Encuentra tus motores de riesgo ocultos",
    lockedCorrTitle: "Ve qué diversifica de verdad", lockedWhyTitle: "Ve el razonamiento por posición",
    unlockPro: "Desbloquear con Pro", unlockFooter: "Desbloquea cada posición, stress tests, correlación y toda la lógica.",
    freePreview: "VISTA PREVIA GRATIS", bannerLineA: "Puedes generar libremente — ", bannerLineB: " revela cada posición y desbloquea stress tests, correlación y toda la lógica.", seePlans: "Ver planes",
  },
  it: {
    heroKicker: "Strumenti", heroFree: " · Gratis",
    heroTitle: "Generatore di portafogli",
    heroSub: "Rispondi a poche domande — o fissa le azioni e gli ETF che già ami — e costruiremo un portafoglio diversificato e ben valutato, sulla misura del tuo importo.",
    heroValidation: "Funziona? Guarda il track record di validazione live →",
    emptyTitle: "Imposta le preferenze, poi genera",
    emptySub: "Costruiremo un portafoglio diversificato e ben valutato — ottimizzato per il miglior rendimento aggiustato per il rischio, sulla tua misura e attorno alle posizioni che fissi.",
    emptyChips: ["Titoli valutati", "Pesi intelligenti", "Proiezione Monte Carlo"],
    pipeGoal: "L'IA legge il tuo obiettivo e seleziona i candidati", pipeGoalSub: "interroga l'universo valutato con i tuoi vincoli",
    pipeScreen: "Screening dell'universo valutato", pipeScreenSub: "ogni pagatore liquido, ordinato per voto composito",
    pipeOpt: "Ottimizzazione Black–Litterman", pipeOptSub: "prior di equilibrio + viste rating e analisti → pesi risolti",
    pipeMeasure: "Misurazione su 10 anni di chiusure reali", pipeMeasureSub: "backtest, replay delle crisi, correlazioni, fattori",
    pipeFooter: "CALCOLATO LIVE — NIENTE È PRECONFEZIONATO",
    panelTitle: "Costruisci il tuo portafoglio", loadErr: "Impossibile caricare i dati di mercato — ricarica per riprovare.",
    s1: "Le basi", s2: "Il tuo obiettivo", s2hint: "facoltativo", s3: "Rifinisci la costruzione",
    amountLabel: "Quanto vuoi investire?", riskLabel: "Tolleranza al rischio", objLabel: "Cosa conta di più?", horizonLabel: "Orizzonte temporale",
    risk: [seg("Prudente", "Meno scossoni, zavorra"), seg("Bilanciato", "La via di mezzo"), seg("Aggressivo", "Più rischio per il rendimento")],
    obj: [seg("Reddito", "Rendimento da dividendo più alto"), seg("Bilanciato", "Reddito + crescita"), seg("Crescita", "Apprezzamento del capitale")],
    horizon: [seg("< 5 anni", "Più zavorra"), seg("5–15 anni", "Bilanciato"), seg("15+ anni", "Più azioni")],
    goalLabel: "Descrivi il tuo obiettivo", goalHint: "lo leggiamo e orientiamo le scelte",
    goalPh: "es. Pensione per un 45enne. Azioni ampie con zavorra obbligazionaria e un po' di estero. A mio agio con −25%, non −40%.",
    goalChips: ["reddito da dividendi", "innovazione tech", "internazionale", "preservazione del capitale"],
    targetLabel: "Patrimonio obiettivo", targetHint: "dove vuoi arrivare", monthlyLabel: "Versamento mensile", monthlyHint: "aggiunto ogni mese", monthlyPh: "es. 100",
    marketLabel: "Focus di mercato", marketHint: "azioni da questo mercato; gli ETF core restano globali",
    marketModalTitle: "Focus di mercato", marketModalSub: "Scegli fino a 4 mercati — o lascia globale. Gli ETF core restano comunque globali.", marketDone: "Fatto",
    marketGlobal: "Nessuna preferenza · Globale", marketSelected: (n, max) => (n === 0 ? "Globale" : `${n} selezionati · max ${max}`),
    sectorsLabel: "Favorire dei settori?", sectorsHint: "vuoto = tutti",
    anchorsLabel: "Costruire attorno a posizioni precise?", anchorsHint: "costruiremo il resto attorno",
    anchorsPh: "Cerca un'azione o un ETF — es. AAPL, SCHD, O", anchorsPhMore: "Aggiungine un altro…", allTickers: "Tutti i titoli",
    countLabel: "Numero di posizioni", countFocused: "5 · concentrato", countSpread: "20 · distribuito",
    generate: "Genera il mio portafoglio", regenerate: "Rigenera", building: "Costruzione — carico i dati di mercato…",
    yourPortfolio: "Il tuo portafoglio generato",
    optimizationMeta: (label, n, amount) => `Ottimizzazione ${label} · ${n} posizioni · per ${amount}`,
    measured: "MISURATO · STORICO REALE", measuring: "MISURAZIONE…", modelled: "STIME DEL MODELLO", blOptimized: "OTTIMIZZATO BLACK–LITTERMAN",
    costToImplement: (bps) => `costo stimato di implementazione ~${bps} pb`, aiRead: "L'IA HA LETTO:",
    thesis: "Tesi del portafoglio", frontier: "Sei portafogli di frontiera", corr: "Matrice di correlazione", assetMix: "Mix di attivi", allocation: "Allocazione consigliata",
    thHolding: "Posizione", thRating: "Voto", thWeight: "Peso", thAmount: "Importo", thYield: "Rendim.",
    stats: "Gli otto numeri che contano", monteCarlo: "Proiezione Monte Carlo", backtest: "Backtest storico · chiusure reali",
    stress: "Stress test storici", riskContrib: "Contributo al rischio", factor: "Esposizione fattoriale · vs S&P 500", sectorExposure: "Esposizione settoriale",
    whyGrade: "Perché questo voto", audit: "Audit IA · rating e notizie live", analysis: "Analisi IA", picksWhy: "Perché queste scelte", legendary: "Confronto con i portafogli leggendari",
    downloadCsv: "Scarica l'allocazione (CSV)", openHealthcheck: "Apri nel Check",
    bannerTitle: "Sei nell'anteprima gratuita", bannerSub: "Genera liberamente — passa a Pro per rivelare ogni posizione e l'intero kit di rischio.",
    bannerCtaPro: "Sblocca con Pro", bannerCtaFree: "Crea un account gratuito",
    lockedStressTitle: "Stress test contro ogni crisi moderna", lockedRiskTitle: "Trova i tuoi driver di rischio nascosti",
    lockedCorrTitle: "Vedi cosa diversifica davvero", lockedWhyTitle: "Vedi il ragionamento per posizione",
    unlockPro: "Sblocca con Pro", unlockFooter: "Sblocca ogni posizione, stress test, correlazione e l'intera logica.",
    freePreview: "ANTEPRIMA GRATUITA", bannerLineA: "Puoi generare liberamente — ", bannerLineB: " rivela ogni posizione e sblocca stress test, correlazione e l'intera logica.", seePlans: "Vedi i piani",
  },
};
