import type { Locale } from "@/lib/i18n";

// Localized checkout copy (/go-pro). Billing/legal sentences are deliberately
// literal and conservative. SSR renders English; locale applies on hydration.
export type GoProStr = {
  secure: string; back: string;
  stepAccount: string; stepPayment: string;
  acctTitle: string; acctSub: string; orEmail: string;
  emailLabel: string; emailPh: string; emailErr: string;
  pwLabel: string; pwHint: string; pwPh: string; pwErr: string;
  pw2Label: string; pw2Ph: string; pw2Err: string;
  pwMeter: [string, string, string, string, string];
  acctCta: string; haveAccount: string; signIn: string;
  planLabel: string; planNote: string; badge: string; productTagline: string;
  included: string[]; includedHead: string;
  rowAnnual: string; rowVat: string; rowVatVal: string; total: string;
  promoApplied: (code: string) => string; renews: string;
  trust: [string, string, string, string];
  signedIn: string; reviewTitle: string; reviewPre: string; reviewPost: string;
  payCta: string; notYou: string; otherAccount: string;
  stripeFoot: string;
  msgRedirect: string; msgCreating: string; redirectSub: string;
  errCheckout: string; errSession: string; errGeneric: string; errExists: string; errSso: string; errStart: string;
  errTitle: string; tryAgain: string;
};

const promoEn = (c: string) => `Promo code ${c} will be applied at checkout`;

export const GOPRO_STR: Record<Locale, GoProStr> = {
  en: {
    secure: "Secure checkout", back: "← Back to pricing",
    stepAccount: "Account", stepPayment: "Payment",
    acctTitle: "Create your account",
    acctSub: "This is how you'll sign in and manage your subscription. One minute, then straight to secure payment — no email confirmation needed.",
    orEmail: "OR WITH EMAIL",
    emailLabel: "Email address", emailPh: "you@example.com", emailErr: "Enter a valid email address",
    pwLabel: "Password", pwHint: "min. 6 characters", pwPh: "Create a password", pwErr: "At least 6 characters",
    pw2Label: "Confirm password", pw2Ph: "Re-enter your password", pw2Err: "Passwords don't match",
    pwMeter: ["Too short", "Weak", "Okay", "Good", "Strong"],
    acctCta: "Continue to secure payment", haveAccount: "Already have an account?", signIn: "Sign in",
    planLabel: "Annual plan", planNote: "Billed once a year", badge: "BEST VALUE", productTagline: "Everything uncoverd, one flat price",
    includedHead: "What's included",
    included: [
      "A–F dividend rating on every stock",
      "Model portfolios & curated best-of lists",
      "Portfolio Healthcheck — full holdings & weights",
      "Dividend watchlist with alerts",
      "CSV exports & advanced screener filters",
      "Completely ad-free",
    ],
    rowAnnual: "Premium annual", rowVat: "VAT", rowVatVal: "Included", total: "Total due today",
    promoApplied: promoEn, renews: "Renews at $100/year. Cancel anytime. Have a promo code? Enter it at checkout.",
    trust: ["Secured by Stripe", "Encrypted in transit", "Cancel anytime", "Instant access"],
    signedIn: "Signed in", reviewTitle: "Review & pay",
    reviewPre: "You're signed in as ", reviewPost: ". One click and you'll complete the upgrade on Stripe's secure checkout.",
    payCta: "Continue to secure payment — $100.00/yr", notYou: "Not you?", otherAccount: "Use another account",
    stripeFoot: "Payment is processed securely by Stripe. We never see or store your card.",
    msgRedirect: "Redirecting to secure payment…", msgCreating: "Creating your account…",
    redirectSub: "One moment — taking you to Stripe's secure checkout.",
    errCheckout: "We couldn't start checkout — please try again.", errSession: "Your session expired — please sign in again.",
    errGeneric: "Could not start checkout.", errExists: "That email already has an account — please sign in to upgrade.",
    errSso: "Couldn't start social sign-in. Try email instead.", errStart: "Something went wrong. Please try again.",
    errTitle: "Couldn't start checkout", tryAgain: "Try again",
  },
  fr: {
    secure: "Paiement sécurisé", back: "← Retour aux tarifs",
    stepAccount: "Compte", stepPayment: "Paiement",
    acctTitle: "Créez votre compte",
    acctSub: "C'est avec ce compte que vous vous connecterez et gérerez votre abonnement. Une minute, puis directement au paiement sécurisé — sans confirmation d'e-mail.",
    orEmail: "OU PAR E-MAIL",
    emailLabel: "Adresse e-mail", emailPh: "vous@exemple.com", emailErr: "Saisissez une adresse e-mail valide",
    pwLabel: "Mot de passe", pwHint: "min. 6 caractères", pwPh: "Créez un mot de passe", pwErr: "Au moins 6 caractères",
    pw2Label: "Confirmez le mot de passe", pw2Ph: "Saisissez à nouveau votre mot de passe", pw2Err: "Les mots de passe ne correspondent pas",
    pwMeter: ["Trop court", "Faible", "Correct", "Bon", "Fort"],
    acctCta: "Continuer vers le paiement sécurisé", haveAccount: "Déjà un compte ?", signIn: "Se connecter",
    planLabel: "Formule annuelle", planNote: "Facturé une fois par an", badge: "MEILLEUR PRIX", productTagline: "Tout uncoverd, un prix unique",
    includedHead: "Ce qui est inclus",
    included: [
      "Notation A–F des dividendes sur chaque action",
      "Portefeuilles modèles & listes des meilleurs",
      "Bilan de portefeuille — positions & pondérations complètes",
      "Watchlist avec alertes dividendes",
      "Exports CSV & filtres avancés du screener",
      "Entièrement sans publicité",
    ],
    rowAnnual: "Premium annuel", rowVat: "TVA", rowVatVal: "Incluse", total: "Total à payer aujourd'hui",
    promoApplied: (c) => `Le code promo ${c} sera appliqué au paiement`,
    renews: "Renouvellement à 100 $/an. Résiliable à tout moment. Un code promo ? Saisissez-le au paiement.",
    trust: ["Sécurisé par Stripe", "Chiffré en transit", "Résiliable à tout moment", "Accès instantané"],
    signedIn: "Connecté", reviewTitle: "Vérifier & payer",
    reviewPre: "Vous êtes connecté en tant que ", reviewPost: ". Un clic et vous finalisez la mise à niveau sur le paiement sécurisé de Stripe.",
    payCta: "Continuer vers le paiement sécurisé — 100,00 $/an", notYou: "Ce n'est pas vous ?", otherAccount: "Utiliser un autre compte",
    stripeFoot: "Le paiement est traité de façon sécurisée par Stripe. Nous ne voyons ni ne stockons jamais votre carte.",
    msgRedirect: "Redirection vers le paiement sécurisé…", msgCreating: "Création de votre compte…",
    redirectSub: "Un instant — nous vous emmenons vers le paiement sécurisé de Stripe.",
    errCheckout: "Impossible de démarrer le paiement — veuillez réessayer.", errSession: "Votre session a expiré — reconnectez-vous.",
    errGeneric: "Impossible de démarrer le paiement.", errExists: "Cet e-mail a déjà un compte — connectez-vous pour passer Pro.",
    errSso: "Impossible de lancer la connexion sociale. Essayez par e-mail.", errStart: "Une erreur est survenue. Veuillez réessayer.",
    errTitle: "Impossible de démarrer le paiement", tryAgain: "Réessayer",
  },
  de: {
    secure: "Sicherer Checkout", back: "← Zurück zu den Preisen",
    stepAccount: "Konto", stepPayment: "Zahlung",
    acctTitle: "Konto erstellen",
    acctSub: "Damit meldest du dich an und verwaltest dein Abo. Eine Minute, dann direkt zur sicheren Zahlung — keine E-Mail-Bestätigung nötig.",
    orEmail: "ODER PER E-MAIL",
    emailLabel: "E-Mail-Adresse", emailPh: "du@beispiel.de", emailErr: "Gültige E-Mail-Adresse eingeben",
    pwLabel: "Passwort", pwHint: "mind. 6 Zeichen", pwPh: "Passwort erstellen", pwErr: "Mindestens 6 Zeichen",
    pw2Label: "Passwort bestätigen", pw2Ph: "Passwort erneut eingeben", pw2Err: "Passwörter stimmen nicht überein",
    pwMeter: ["Zu kurz", "Schwach", "Okay", "Gut", "Stark"],
    acctCta: "Weiter zur sicheren Zahlung", haveAccount: "Schon ein Konto?", signIn: "Anmelden",
    planLabel: "Jahresplan", planNote: "Einmal jährlich abgerechnet", badge: "BESTER WERT", productTagline: "Alles von uncoverd, ein Festpreis",
    includedHead: "Das ist enthalten",
    included: [
      "A–F-Dividendenrating für jede Aktie",
      "Modellportfolios & kuratierte Bestenlisten",
      "Portfolio-Check — alle Positionen & Gewichte",
      "Dividenden-Watchlist mit Alerts",
      "CSV-Exporte & erweiterte Screener-Filter",
      "Komplett werbefrei",
    ],
    rowAnnual: "Premium jährlich", rowVat: "MwSt.", rowVatVal: "Inklusive", total: "Heute fällig",
    promoApplied: (c) => `Promo-Code ${c} wird beim Checkout angewendet`,
    renews: "Verlängert sich zu 100 $/Jahr. Jederzeit kündbar. Promo-Code? Beim Checkout eingeben.",
    trust: ["Gesichert durch Stripe", "Verschlüsselt übertragen", "Jederzeit kündbar", "Sofortiger Zugang"],
    signedIn: "Angemeldet", reviewTitle: "Prüfen & bezahlen",
    reviewPre: "Du bist angemeldet als ", reviewPost: ". Ein Klick, und du schließt das Upgrade in Stripes sicherem Checkout ab.",
    payCta: "Weiter zur sicheren Zahlung — 100,00 $/Jahr", notYou: "Nicht du?", otherAccount: "Anderes Konto verwenden",
    stripeFoot: "Die Zahlung wird sicher von Stripe verarbeitet. Wir sehen und speichern deine Karte nie.",
    msgRedirect: "Weiterleitung zur sicheren Zahlung…", msgCreating: "Konto wird erstellt…",
    redirectSub: "Einen Moment — wir bringen dich zu Stripes sicherem Checkout.",
    errCheckout: "Checkout konnte nicht gestartet werden — bitte erneut versuchen.", errSession: "Deine Sitzung ist abgelaufen — bitte erneut anmelden.",
    errGeneric: "Checkout konnte nicht gestartet werden.", errExists: "Für diese E-Mail existiert bereits ein Konto — bitte anmelden, um upzugraden.",
    errSso: "Social-Login konnte nicht gestartet werden. Versuche es per E-Mail.", errStart: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    errTitle: "Checkout konnte nicht gestartet werden", tryAgain: "Erneut versuchen",
  },
  es: {
    secure: "Pago seguro", back: "← Volver a precios",
    stepAccount: "Cuenta", stepPayment: "Pago",
    acctTitle: "Crea tu cuenta",
    acctSub: "Con ella iniciarás sesión y gestionarás tu suscripción. Un minuto y directo al pago seguro — sin confirmación de correo.",
    orEmail: "O CON CORREO",
    emailLabel: "Correo electrónico", emailPh: "tu@ejemplo.com", emailErr: "Introduce un correo válido",
    pwLabel: "Contraseña", pwHint: "mín. 6 caracteres", pwPh: "Crea una contraseña", pwErr: "Al menos 6 caracteres",
    pw2Label: "Confirma la contraseña", pw2Ph: "Vuelve a escribir tu contraseña", pw2Err: "Las contraseñas no coinciden",
    pwMeter: ["Demasiado corta", "Débil", "Aceptable", "Buena", "Fuerte"],
    acctCta: "Continuar al pago seguro", haveAccount: "¿Ya tienes cuenta?", signIn: "Inicia sesión",
    planLabel: "Plan anual", planNote: "Un único cobro al año", badge: "MEJOR VALOR", productTagline: "Todo uncoverd, un precio plano",
    includedHead: "Qué incluye",
    included: [
      "Calificación A–F de dividendos en cada acción",
      "Carteras modelo y listas de los mejores",
      "Chequeo de cartera — posiciones y pesos completos",
      "Watchlist con alertas de dividendos",
      "Exportes CSV y filtros avanzados del screener",
      "Completamente sin anuncios",
    ],
    rowAnnual: "Premium anual", rowVat: "IVA", rowVatVal: "Incluido", total: "Total a pagar hoy",
    promoApplied: (c) => `El código promocional ${c} se aplicará en el pago`,
    renews: "Se renueva a 100 $/año. Cancela cuando quieras. ¿Tienes un código? Introdúcelo en el pago.",
    trust: ["Asegurado por Stripe", "Cifrado en tránsito", "Cancela cuando quieras", "Acceso instantáneo"],
    signedIn: "Sesión iniciada", reviewTitle: "Revisar y pagar",
    reviewPre: "Has iniciado sesión como ", reviewPost: ". Un clic y completarás la mejora en el pago seguro de Stripe.",
    payCta: "Continuar al pago seguro — 100,00 $/año", notYou: "¿No eres tú?", otherAccount: "Usar otra cuenta",
    stripeFoot: "El pago lo procesa Stripe de forma segura. Nunca vemos ni guardamos tu tarjeta.",
    msgRedirect: "Redirigiendo al pago seguro…", msgCreating: "Creando tu cuenta…",
    redirectSub: "Un momento — te llevamos al pago seguro de Stripe.",
    errCheckout: "No pudimos iniciar el pago — inténtalo de nuevo.", errSession: "Tu sesión ha caducado — inicia sesión de nuevo.",
    errGeneric: "No se pudo iniciar el pago.", errExists: "Ese correo ya tiene una cuenta — inicia sesión para mejorar a Pro.",
    errSso: "No se pudo iniciar el acceso social. Prueba con el correo.", errStart: "Algo salió mal. Inténtalo de nuevo.",
    errTitle: "No se pudo iniciar el pago", tryAgain: "Reintentar",
  },
  it: {
    secure: "Pagamento sicuro", back: "← Torna ai prezzi",
    stepAccount: "Account", stepPayment: "Pagamento",
    acctTitle: "Crea il tuo account",
    acctSub: "Con questo accederai e gestirai il tuo abbonamento. Un minuto, poi dritto al pagamento sicuro — senza conferma e-mail.",
    orEmail: "OPPURE VIA E-MAIL",
    emailLabel: "Indirizzo e-mail", emailPh: "tu@esempio.com", emailErr: "Inserisci un'e-mail valida",
    pwLabel: "Password", pwHint: "min. 6 caratteri", pwPh: "Crea una password", pwErr: "Almeno 6 caratteri",
    pw2Label: "Conferma password", pw2Ph: "Reinserisci la password", pw2Err: "Le password non coincidono",
    pwMeter: ["Troppo corta", "Debole", "Discreta", "Buona", "Forte"],
    acctCta: "Continua al pagamento sicuro", haveAccount: "Hai già un account?", signIn: "Accedi",
    planLabel: "Piano annuale", planNote: "Addebito una volta l'anno", badge: "MIGLIOR VALORE", productTagline: "Tutto uncoverd, un prezzo unico",
    includedHead: "Cosa è incluso",
    included: [
      "Valutazione A–F dei dividendi su ogni azione",
      "Portafogli modello e liste dei migliori",
      "Check del portafoglio — posizioni e pesi completi",
      "Watchlist con avvisi sui dividendi",
      "Esportazioni CSV e filtri avanzati dello screener",
      "Completamente senza pubblicità",
    ],
    rowAnnual: "Premium annuale", rowVat: "IVA", rowVatVal: "Inclusa", total: "Totale dovuto oggi",
    promoApplied: (c) => `Il codice promo ${c} sarà applicato al pagamento`,
    renews: "Si rinnova a 100 $/anno. Disdici quando vuoi. Hai un codice promo? Inseriscilo al pagamento.",
    trust: ["Protetto da Stripe", "Crittografato in transito", "Disdici quando vuoi", "Accesso immediato"],
    signedIn: "Accesso effettuato", reviewTitle: "Rivedi e paga",
    reviewPre: "Hai effettuato l'accesso come ", reviewPost: ". Un clic e completerai l'upgrade nel pagamento sicuro di Stripe.",
    payCta: "Continua al pagamento sicuro — 100,00 $/anno", notYou: "Non sei tu?", otherAccount: "Usa un altro account",
    stripeFoot: "Il pagamento è elaborato in modo sicuro da Stripe. Non vediamo né salviamo mai la tua carta.",
    msgRedirect: "Reindirizzamento al pagamento sicuro…", msgCreating: "Creazione del tuo account…",
    redirectSub: "Un attimo — ti portiamo al pagamento sicuro di Stripe.",
    errCheckout: "Impossibile avviare il pagamento — riprova.", errSession: "La tua sessione è scaduta — accedi di nuovo.",
    errGeneric: "Impossibile avviare il pagamento.", errExists: "Quell'e-mail ha già un account — accedi per passare a Pro.",
    errSso: "Impossibile avviare l'accesso social. Prova con l'e-mail.", errStart: "Qualcosa è andato storto. Riprova.",
    errTitle: "Impossibile avviare il pagamento", tryAgain: "Riprova",
  },
};
